---
title: "Prediction with sPLS"
output:
  html_document:
    theme: united
    toc: yes
    toc_float:
      collapsed: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Introduction

Create a prediction model for detecting lesional status via the genes.


## Preparation

Install packages and load the data. 

```{r message=FALSE}
# reset console
cat('\014')
rm(list=ls())

packages <- c('ggplot2',
              'rstudioapi',
              'data.table',
              'mixOmics',
              'SuperLearner',
              'parallel')

if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")

for (pkg in packages){
  tryCatch(
  if (!(pkg %in% rownames(installed.packages()))){
    install.packages(pkg)
  }, error=function(e){
    BiocManager::install(pkg) # try installing with BiocManager
  })
}

library('ggplot2')
library('rstudioapi')
library('data.table')
library('mixOmics')
library('caret') # invokes xgboost
library("SuperLearner")
library('parallel')



# loading datasets
samples <- read.csv('../filter-data/all.csv')
samples <- subset(samples, samples$clinical_group == 'AD')

# read in transcriptome data, change row names and remove the var 'X'
transcriptome <- read.csv('../filter-data/transcriptome.csv') # takes time to load
rownames(transcriptome) <- transcriptome$X
transcriptome <- transcriptome[,-c(1)]

# keep the transcriptomes that are AD
transcriptome <- transcriptome[rownames(transcriptome) %in% samples$sample_id,]
# create an index, matching the sample_id to the row in the transcriptome
indices <- match(samples$sample_id, rownames(transcriptome))
# stop the process if there's any lines that have NA (sample_id has not matching transcriptome)
stopifnot(sum(is.na(indices)) == 0)
transcriptome <- transcriptome[indices,]



#lesion <- 2-as.integer(samples$lesional)
samples$lesional_new[samples$lesional=="LES"]<- 1
samples$lesional_new[samples$lesional=="NON_LES"]<- 0   
```


## sPLS

```{r message=FALSE}
n_components <- 10
list.keepX <- c(2:10, 15, 20)

set.seed(1)

tune.Mfold <- tune.spls(X=transcriptome,
                        Y=samples$lesional_new,
                        ncomp=n_components,
                        test.keepX=list.keepX,
                        validation = "Mfold",
                        folds=10, # initially 10
                        measure = "MSE",
                        progressBar = TRUE)


cumul_gene_names <- c()

spls <- mixOmics::splsda(transcriptome, 
                         samples$lesional_new, 
                         ncomp=n_components,
                         keepX=as.vector(tune.Mfold$choice.keepX))

for (i in 1:n_components){
  temp_component <- spls$loadings$X[,i]
  temp_component <- temp_component[temp_component != 0]
  cumul_gene_names <- c(names(temp_component), cumul_gene_names)
}

length(cumul_gene_names)

#write.table(cumul_gene_names, file='../genelist_spls_Mfold.txt')
```

## Prediction model using ensemble learning

This part was ultimately not included in the final report due to logical errors in output and time restrictions.

```{r}
selected_genes <- c('ENSG00000186832', 
                    'ENSG00000124102', 
                    'ENSG00000165474', 
                    'ENSG00000172382', 
                    'ENSG00000198074', 
                    'ENSG00000163220', 
                    'ENSG00000163221') # manually entered, genes found through DGE and sPLS

models <- list('SL.ranger', 
               'SL.glm', 
               'SL.ksvm',
               'SL.xgboost',
               'SL.nnet',
               'SL.mean')


colnames(transcriptome) <- substr(colnames(transcriptome), 1, nchar(colnames(transcriptome)[1])-3)
transcriptome <- transcriptome[,colnames(transcriptome) %in% selected_genes]

sl <- SuperLearner(Y=samples$lesional_new,
                   X=transcriptome,
                   family=binomial(),
                   SL.library=models)

if (parallel::detectCores() > 8){
  num_folds <- length(samples$lesional_new)
  cat('Using multiprocessing for leave-one-out cross-validation\n')
} else{
  num_folds <- 5
  cat('Not enough computational power... using 5-fold cross-validation')
}

cv.sl <- CV.SuperLearner(Y=samples$lesional_new,
                         X=transcriptome,
                         V=num_folds, # ideally use n for leave-out-one cross-validation
                         family=binomial(),
                         SL.library=models)

predictions <- predict.SuperLearner(cv.sl)$pred

source('utils.R') # importing functions from another R script

plot.roc(predictions, samples$lesional_new)
ggsave('roc_curve.png', width=7, height=4.5, units='in', dpi=250)
```

